# -*- coding: utf-8 -*-
"""Spotify Recommender System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkZo6R_BKQ-G7pBvqHJga-iiAM5Wiosf
"""

import pandas as pd

pip install kaggle

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d notshrirang/spotify-million-song-dataset

from zipfile import ZipFile
dataset='/content/spotify-million-song-dataset.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print("Dataset is extracted")

df=pd.read_csv('/content/spotify_millsongdata.csv')

df.head()

df.shape

#Checking for any null values
df.isnull().sum()

#Removing the link column

df =df.sample(5000).drop('link', axis=1).reset_index(drop=True)

# df=data.sample(5000)
# df.shape
# df['text'][0]
df.head()

"""Text Cleaning"""

df['text']=df['text'].str.lower().replace(r'^\W\S',' ').replace(r'\n',' ',regex=True)  #Removing all tab space characters

df.head()

import nltk
from nltk.stem.porter import PorterStemmer

stemmer=PorterStemmer()

def token(text):
  token=nltk.word_tokenize(text)
  a=[stemmer.stem(w) for w in token]
  return " ".join(a)

import nltk
nltk.download('punkt')

token("What You See Is What You Don't Get")

df['text']=df['text'].apply(lambda x: token(x))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfid=TfidfVectorizer(analyzer='word',stop_words='english')

matrix=tfid.fit_transform(df['text'])

similar=cosine_similarity(matrix)
similar

"""Song Recommender Function"""

def recommender(song_name):
  idx=df[df['song']==song_name].index[0]
  distance=sorted(list(enumerate(similar[idx])),reverse=True, key= lambda x:x[1])
  song=[]
  for s_id in distance[1:5]:
    song.append(df.iloc[s_id[0]].song)
  return song

recommender('Flight 602')